version: '3.3'

services:
  db:
    image: "postgres:9.6"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=debunkbot
      - POSTGRES_PASSWORD=debunkbot
      - POSTGRES_DB=debunkbot
    ports:  # Added this so I can access the database from outside the container
      - "5432:5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  app:
    restart: always
    build:
      context: .
      target: app-ci
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - db
      - redis
    environment:
      - DEBUNKBOT_GUNICORN_TIMEOUT=${DEBUNKBOT_GUNICORN_TIMEOUT:-120}
      - DEBUNKBOT_GUNICORN_WORKERS=${DEBUNKBOT_GUNICORN_WORKERS:-3}
    stdin_open: true
    tty: true

volumes:
  postgres_data:
