version: '3.3'

services:
  db:
    image: "postgres:12.2"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=debunkbot
      - POSTGRES_PASSWORD=debunkbot
      - POSTGRES_DB=debunkbot
    ports:  # Added this so I can access the database from outside the container
      - "5432:5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  web:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment: 
      - DEBUNKBOT_GUNICORN_TIMEOUT=${DEBUNKBOT_GUNICORN_TIMEOUT:-120}
      - DEBUNKBOT_GUNICORN_WORKERS=${DEBUNKBOT_GUNICORN_WORKERS:-3}
    stdin_open: true
    tty: true  
  celery:
    image: debunkbot-celery
    build: .
    command: celery -A debunkbot worker --app=debunkbot.celeryapp:app -l info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
  celery-beat:
    image: debunkbot-celery-beat
    build: .
    command: celery -A debunkbot beat --app=debunkbot.celeryapp:app -l info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
  flower:
    image: mher/flower:0.9.5
    command: ['flower', '--broker=redis://redis:6379', '--port=5555', '--basic_auth=root:randompassword']
    ports:
      - 5557:5555
    depends_on:
      - redis
volumes:
  postgres_data:
