version: '3.3'

services:
  db:
    image: "postgres:12.2"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=debunkbot
      - POSTGRES_PASSWORD=debunkbot
      - POSTGRES_DB=debunkbot
    ports:  # Added this so I can access the database from outside the container
      - "5432:5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  web:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A debunkbot worker -l info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A debunkbot beat -l info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
