# Generated by Django 2.2 on 2020-05-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='saved_to_sheet',
            new_name='processed',
        ),
    ]
