# Generated by Django 2.2 on 2020-05-12 05:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0002_auto_20200511_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='impact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_id',
            field=models.CharField(default=0, help_text='The Id of the reply we send to this tweet', max_length=255),
            preserve_default=False,
        ),
    ]
