# Generated by Django 2.2 on 2020-05-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0004_add_impact_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.CharField(help_text='Message template to use for sending reply', max_length=255)),
            ],
        ),
    ]
