# Generated by Django 2.2 on 2020-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0004_add_impact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='processed',
            field=models.BooleanField(
                default=False,
                help_text="Determines if we've processed tweets related to this claim or not"),
        ),
        migrations.AlterField(
            model_name='impact',
            name='replies_count',
            field=models.IntegerField(help_text='Number of replies we have received on our reply.'),
        ),
    ]
