# Generated by Django 2.2 on 2020-05-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0004_add_reply_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='reply_author',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='reply_id',
        ),
    ]
