# Generated by Django 2.2 on 2020-06-05 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The spreadsheet id for the database we're pulling from", max_length=255)),
                ('workspaces', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='List of workspaces to fetch data from', size=None)),
                ('claim_url_column', models.CharField(help_text='The column to fetch claim urls from in this specific spreadsheet', max_length=5)),
                ('claim_phrase_column', models.CharField(help_text='The column to fetch claim phrases from in this specific spreadsheet', max_length=5)),
                ('claim_rating_column', models.CharField(help_text='The column to fetch claim rating from in this specific spreadsheet', max_length=5)),
                ('claim_checked_column', models.CharField(help_text='The column to fetch claim rating from in this specific spreadsheet', max_length=5)),
                ('claim_debunk_url_column', models.CharField(help_text='The column to fetch claim rating from in this specific spreadsheet', max_length=5)),
            ],
        ),
    ]
