# Generated by Django 2.2 on 2020-05-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0005_auto_20200521_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message to reply with to a false claim.', max_length=255)),
            ],
        ),
    ]
