# Generated by Django 2.2 on 2020-06-09 11:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0006_gsheetclaimsdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebunkBotGsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, help_text='The database name from which the claims were fetched from.', max_length=255, null=True)),
                ('db_link', models.CharField(blank=True, help_text='The database link from which the claims were fetched from.', max_length=255, null=True)),
                ('claim_appearance', models.URLField(blank=True, help_text='A link to where the claim appeared. This will mostly be twitter', max_length=255, null=True)),
                ('claim_sender', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='All available info about the claim sender.', null=True)),
                ('debunkbot_reply', models.CharField(blank=True, help_text='The response which the debunkbot sent.', max_length=255, null=True)),
                ('likes_count', models.CharField(blank=True, help_text='Number of likes the bot reply received', max_length=10, null=True)),
                ('retweets_count', models.CharField(blank=True, help_text='Number of retweets the bot reply received', max_length=10, null=True)),
                ('replies_count', models.CharField(blank=True, help_text='Number of replies the bot reply received', max_length=10, null=True)),
                ('replies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, help_text='The replies the bot reply received', null=True, size=None)),
                ('tweet_deleted', models.BooleanField(default=False, help_text='Has the tweet the bot replied to been deleted?')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debunk_bot_gsheet', to='debunkbot.Claim')),
            ],
        ),
    ]
