# Generated by Django 2.2 on 2020-07-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0009_message_template_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondListGsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key of the Google Sheet holding the respond to list.', max_length=255)),
                ('worksheet_name', models.CharField(help_text='The name of the workspace containing the respond to accounts', max_length=255)),
                ('column_name', models.CharField(help_text='The column name containing the respond to accounts.', max_length=255)),
            ],
        ),
    ]
