# Generated by Django 2.2 on 2020-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debunkbot', '0010_respondlistgsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_mode', models.CharField(choices=[('No Responses', 'Send No Response'), ('Response List', 'Use a Response List'), ('Open Response', 'Send Responses to any twitter account')], help_text='Current response mode', max_length=255, verbose_name='Which response mode do you want to use?')),
            ],
        ),
    ]
