# Generated by Django 2.2 on 2020-08-24 13:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debunkbot", "0011_responsemode"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteClaimsDatabase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the website.", max_length=225),
                ),
                ("url", models.URLField()),
            ],
            options={"db_table": "website_claims_database",},
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="message_template_category",
            field=models.CharField(
                blank=True,
                help_text="Category that this message template belongs to.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Post title.", max_length=255)),
                ("link", models.URLField(help_text="Post link.")),
                (
                    "first_appearance",
                    models.URLField(
                        help_text="First appearance of the story in this post."
                    ),
                ),
                (
                    "appearances",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        help_text="Link to other places that the story appeared.",
                        size=None,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when this post was created."),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location where this story happened.", max_length=255
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="debunkbot.WebsiteClaimsDatabase",
                    ),
                ),
            ],
            options={"db_table": "posts",},
        ),
    ]
