# Generated by Django 2.2 on 2020-08-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("debunkbot", "0012_website_and_post_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="claim", name="claim_db",),
        migrations.AddField(
            model_name="claim",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
