# Generated by Django 2.2 on 2020-09-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debunkbot", "0013_add_website_claims_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="claim_author",
            field=models.CharField(
                blank=True,
                help_text="The author of the claim",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_date",
            field=models.CharField(
                blank=True,
                help_text="The date when the claim was made.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_db",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="debunkbot.ClaimsDatabase",
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_first_appearance",
            field=models.TextField(
                blank=True,
                help_text="Link to where the claim first appeared.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_location",
            field=models.CharField(
                blank=True,
                help_text="The location where the claim was made.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="claim_phrase",
            field=models.CharField(
                blank=True,
                help_text="Claim phrase that we should track.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="fact_checked_url",
            field=models.TextField(
                blank=True, help_text="The URL to the debunked claim.", null=True
            ),
        ),
    ]
