# Generated by Django 2.2 on 2020-09-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debunkbot", "0016_use_datefield_for_claim_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsheetclaimsdatabase",
            name="claim_date_column_name",
            field=models.CharField(
                blank=True,
                help_text="The column to fetch claim date from in this specific spreadsheet",
                max_length=255,
                null=True,
            ),
        ),
    ]
