# Generated by Django 2.2 on 2020-12-04 09:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debunkbot", "0018_claimstracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="claim_appearances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                help_text="Links to where the claims appeared, comma separated.",
                null=True,
                size=None,
            ),
        ),
    ]
