# Generated by Django 2.2.24 on 2021-08-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debunkbot", "0020_prevent_null_factchecked_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabasePriority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low", models.IntegerField(default=15, help_text="Low priority.")),
                (
                    "normal",
                    models.IntegerField(default=35, help_text="Normal priority."),
                ),
                ("high", models.IntegerField(default=50, help_text="High priority.")),
            ],
        ),
    ]
