# Generated by Django 2.2.24 on 2021-08-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debunkbot", "0022_claimdatabasepriority"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasepriority",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Is this the active database priority?"
            ),
        ),
        migrations.AddConstraint(
            model_name="databasepriority",
            constraint=models.UniqueConstraint(
                condition=models.Q(active=True),
                fields=("active",),
                name="unique_active_priority",
            ),
        ),
    ]
