# Generated by Django 3.2 on 2022-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debunkbot", "0026_auto_20220127_0245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesheetcredentials",
            name="credentials",
            field=models.JSONField(
                help_text="The service account key needed by \
                    the application to access Google Sheet data."
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="reply",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="tweet",
            field=models.JSONField(),
        ),
    ]
