name: Run test on pull request

on:
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
    ]

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: make build
      - name: Start app
        run: make run
      - name: Run tests
        run: make test
      - name: Stop app
        run: make stop
