name: CI/CD

on:
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
    ]
jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Build the Docker image
        uses: actions/checkout@v2
        run: |
          make build
          echo "DEBUNKBOT_CACHE_TTL=60" >> .env
          echo "DEBUNKBOT_TEST_GSHEET_SHEET_ID=${{ secrets.DEBUNKBOT_TEST_GSHEET_SHEET_ID }}" >> .env
          echo "DEBUNKBOT_SENTRY_DSN=${{ secrets.DEBUNKBOT_SENTRY_DSN }}" >> .env

      - name: Create credentials.json
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/debunkbot/test/credentials.json
          encodedString: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Start app
        run: make run

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test

      - name: Stop app
        run: make stop
